### ISSUE TITLE
Neovim port

### ISSUE THREAD

**Issue by ghost** [arzg/sema#9]
Thanks for this amazing theme, it has become my standard :)

Is it possible to make a port for neovim? Tbh, I tried to do this myself, but due to the fact that I am just starting to understand the Neovim infrastructure, it just blew my mind...

P.S. Maybe someone already did this?

**Comment by lunacookies** [comment]
Thanks for the kind words :)

I’m not aware of anyone who’s tried porting sema to other editors.

If you’re after the colors and overall “feel” of sema, rather than the emphasis on tricky elements of code, then you have the easy option of using the theme which sema was based on, [grb24bit](https://github.com/garybernhardt/dotfiles/blob/07bbd349eb0480dc07a6514efde30b8223d18b1d/.vim/colors/grb24bit.vim). Copy that file and `ir_black.vim` from the same repo into `~/.config/nvim/colors/`, add

```vim
set termguicolors
colorscheme grb24bit
```

to your `init.vim` and you should be good to go!

---

If you really want sema’s fancy highlighting, then read on …

Sadly, neither Vim nor Neovim by themselves have advanced enough highlighting systems to implement the ideas in sema. For instance, knowing which methods come from an interface is only possible through language intelligence, which regex-based (Vim & Neovim) or syntax-tree based (tree-sitter in Neovim) systems cannot provide.

sema does this kind of advanced highlighting by consuming the semantic tokens provided to VS Code by a language server. These tokens have both a token kind (e.g. `function`) as well as zero or more modifiers (e.g. `trait`). Here’s how sema highlights this scope:

https://github.com/lunacookies/sema/blob/29c2c52da2a6da74505e702a2bef49f2f07201d9/themes/sema-color-theme.json#L76-L79

It seems that nowadays Neovim can also access semantic tokens produced by a language server. I’ve never used this functionality myself so I can’t speak to how well it would work, though [based on this guide](https://gist.github.com/swarn/fb37d9eefe1bc616c2a7e476c0bc0316) I think the equivalent of the above declaration would be

```vim
hi @lsp.function.trait guifg=#75CAF2 guibg=NONE gui=NONE
```

It should be fairly straightforward to change the generator in `src/` to output Vim highlight statements instead of VS Code theme JSON, and I think the result would look identical.

If you’d rather not use the Rust-based generator in this repo, then I can highly recommend [Colortemplate](https://github.com/lifepillar/vim-colortemplate).

Good luck!

**Comment by ghost** [comment]
Thank you very much for your answer and advice, I'll try it :)
